version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
  # Watch dependencies for current stable
  - package-ecosystem: "bundler"
    directory: "/docker-image"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
